# CTest crash_log_module: the crash log names the module that holds a host crash address.
# Runs the game executable with WWHD_TEST_HOST_CRASH=1 (main.cpp: strlen of a bad pointer, right
# after the crash handler is installed; no game files needed) and checks captures/crash-*.log.
# cmake -DWWHD=<wwhd executable> -DWORK=<empty work folder> -P crash_log_test.cmake
file(REMOVE_RECURSE "${WORK}")
file(MAKE_DIRECTORY "${WORK}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E env WWHD_TEST_HOST_CRASH=1 WWHD_NO_AUDIO=1 "WWHD_TEST_CONTEXT_PATH=$ENV{HOME}/crash-test" "${WWHD}"
                WORKING_DIRECTORY "${WORK}" RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 120)
if(rc EQUAL 0)
  message(FATAL_ERROR "the executable did not crash:\n${out}\n${err}")
endif()
file(GLOB logs "${WORK}/captures/crash-*.log")
list(LENGTH logs nlogs)
if(NOT nlogs EQUAL 1)
  message(FATAL_ERROR "expected one crash log in ${WORK}/captures, found ${nlogs} (exit ${rc}):\n${err}")
endif()
file(READ "${logs}" log)
message(STATUS "crash log:\n${log}")
# (a function: a macro would substitute the regex text and lose its backslashes)
function(expect regex what)
  if(NOT log MATCHES "${regex}")
    message(FATAL_ERROR "crash log lacks ${what} (${regex})")
  endif()
  set(match1 "${CMAKE_MATCH_1}" PARENT_SCOPE)
endfunction()
# the faulting instruction: in the C library, not in the game executable
if(WIN32)
  expect("CRASH: Windows exception C0000005 at [0-9A-F]+ in ([^ \n]+)\\+0x[0-9A-F]+ \\(base [0-9A-F]+\\)" "the module of the crash address")
  set(module "${match1}")
  expect("access violation: read of address 0+10\n" "the access type and address")
else()
  expect("host pc 0x[0-9a-f]+ in ([^ \n]+)\\+0x[0-9a-f]+ \\(base 0x[0-9a-f]+\\)" "the module of the crash address")
  set(module "${match1}")
endif()
get_filename_component(exe "${WWHD}" NAME)
if(module STREQUAL exe)
  message(FATAL_ERROR "the crash address was placed in ${module}; strlen lives in the C library")
endif()
expect("\n  module: [^\n]+" "the module's path")
# the host backtrace, frames annotated with their modules (Windows walks from the faulting
# instruction; backtrace() elsewhere starts in the handler and may skip the faulting leaf function)
expect("host backtrace:\n  #0 +[0-9A-Fa-fx]+ in " "an annotated host backtrace")
string(REPLACE "." "\\." exe_re "${exe}")
expect("\n  #[0-9]+ +[0-9A-Fa-fx]+ in ${exe_re}\\+0x" "a backtrace frame in ${exe}")
if(WIN32)
  string(REPLACE "." "\\." module_re "${module}")
  expect("host backtrace:\n  #0 +[0-9A-F]+ in ${module_re}\\+0x" "the faulting frame first in the backtrace")
endif()
# and the log ring
expect("--- last log lines ---\n.*WWHD_TEST_HOST_CRASH" "the last log lines")
message(STATUS "crash address in ${module}: ok")

expect("--- crash context [(]startup[)] ---" "startup settings context")
expect("WWHD_TEST_CONTEXT_PATH=~/crash-test" "redacted environment path")
if(NOT "$ENV{HOME}" STREQUAL "")
  string(FIND "${log}" "$ENV{HOME}" home_pos)
  if(NOT home_pos EQUAL -1)
    message(FATAL_ERROR "crash log contains an unredacted home path")
  endif()
endif()
